name: Verify

# yamllint disable-line rule:truthy
on: [ push, pull_request ]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run EditorConfig Checker
        run: |
          go run github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker@2.7.1 --exclude .git
      - name: Run yamllint
        run: |
          pip install yamllint
          yamllint .
      - uses: bewuethr/shellcheck-action@v2
      - uses: DavidAnson/markdownlint-cli2-action@v13
      - name: Install butane
        run: |
          curl --fail --silent --show-error \
            --location "https://github.com/coreos/butane/releases/download/v${butane_version}/butane-x86_64-unknown-linux-gnu" \
            --output "butane"
          curl --fail --silent --show-error \
            --location "https://github.com/coreos/butane/releases/download/v${butane_version}/butane-x86_64-unknown-linux-gnu.asc" \
            --output "butane.asc"
          curl --silent --show-error "https://fedoraproject.org/fedora.gpg" --output "fedora.gpg"
          gpg --import "fedora.gpg"
          gpg --verify "butane.asc" "butane"
          mv "butane" "/usr/local/bin/butane"
          chmod +x "/usr/local/bin/butane"
        env:
          butane_version: "0.18.0"
      - name: Run butane
        run: |
          find . -type f -name "*.bu.yaml" -o -name "*.bu.yml" | while read -r file; do
            echo "verifying ${file}"
            ./scripts/test.sh --bu-file "${file}"
          done
